# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e202cc970a595ff8ca04263bdba4c267ef3aac57a06b7952e3619b148a844c05f24b7571636c2dbd67711ef9726da53ffbf47db80b1777a99692f254e60305a5

test:
  secret_key_base: d64ddf3f0e94832c66f8f072731a005b639ebfbc23260d850a20b54a98f27535bc2c3d9dfc054b431b09a10f0e273a26c9522422db3c31860043352fd3ab474e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
